on:
  push:
    tags:
      - v*.**
jobs:
  package-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create MikroTik.tar of Splunk app contents
        run: 
          tar -czvf MikroTik.tar -C src/splunk-app .
      - name: Create MikroTik.spl which is the Splunk app format
        run: 
          tar -czvf MikroTik.spl MikroTik.tar
      - name: Create device-scripts.tar of scripts for each MT device
        run:
          tar -czvf device-scripts.tar -C src/mikrotik-scripts .
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: |
            MikroTik.spl
            device-scripts.tar
        
  create-release:
    needs: package-contents
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        run: echo "hello"